# Generated by Django 3.0.8 on 2020-10-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbbroadcastpod',
            name='name',
            field=models.CharField(default='Nameless', max_length=1000),
            preserve_default=False,
        ),
    ]
