# Generated by Django 3.0.8 on 2020-10-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('meetings', '0002_bbbbroadcastpod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbbroadcastpod',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
