# Generated by Django 3.0.8 on 2020-10-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('meetings', '0003_auto_20201016_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbbbroadcastpod',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bbbserver',
            name='category',
        ),
        migrations.RemoveField(
            model_name='streamorigin',
            name='category',
        ),
        migrations.AddField(
            model_name='streamorigin',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='streamorigin',
            name='name',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
