# Generated by Django 3.0.8 on 2020-10-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20201016_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfraCategory',
        ),
    ]
