# Generated by Django 3.0.8 on 2020-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_activitylog_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event',
            field=models.CharField(choices=[('1', 'Logged In'), ('2', 'Logged Out'), ('3', 'Stream Started'), ('4', 'Stream Stopped')], max_length=2),
        ),
    ]
